/**
 * policyAutoSync.js — Policy Auto-Sync Engine (v24.3)
 *
 * Eliminates permission↔policy drift by detecting permissions in the P enum
 * that have no corresponding entry in the policyRegistry, and auto-generating
 * safe default policies at boot time (dev) or crashing (production).
 *
 * SSOT:
 *   Permissions → orgPermissions.js (P enum)
 *   Policies   → policyRegistry.js  (policies object)
 *
 * MODES:
 *   "warn"   — auto-generate missing policies at runtime + log warning (dev)
 *   "strict" — throw if ANY permission lacks a policy (prod / CI)
 *
 * SAFETY RULES:
 *   - Auto-generated policies default to holders of P.STAFF_MANAGE only
 *     (deny all others) — no inline role-name checks per RBAC SSOT rule
 *   - Never condition: () => true for allow (security risk)
 *   - Every generated policy includes a deny fallback rule
 *   - All generated policies are tagged { autoGenerated: true }
 *
 * PLANE: Org only.
 *
 * @module policyAutoSync
 */

"use strict";

const { P } = require("@rbac/orgPermissions");
const { policies } = require("@rbac/policyRegistry");
const logger = require("@utils/logger");

// ─── Default Policy Generator ──────────────────────────────────────────────

/**
 * Generate a safe default policy for a permission that has no explicit rules.
 *
 * The default grants access ONLY to users whose context carries P.STAFF_MANAGE.
 * All other users are denied. This is intentionally restrictive — auto-generated
 * policies must never silently grant broad access.
 *
 * RBAC SSOT: we check the permission Set, never a role name. In the seeded
 * system roles, P.STAFF_MANAGE is exclusive to org_admin, so this preserves
 * prior semantics while remaining compatible with future custom roles.
 *
 * @param {string} permissionKey — The canonical permission string (e.g. "documents.manage")
 * @returns {Array<Object>} — Array of policy rules matching the policyRegistry shape
 */
function generateDefaultPolicy(permissionKey) {
    return [
        {
            effect: "allow",
            description: `[AUTO-GENERATED] STAFF_MANAGE default access for ${permissionKey}`,
            condition: (ctx) => {
                if (!ctx.user) return false;
                // Prefer the authoritative permission Set from req.context.
                const perms = ctx.permissions || ctx.user.permissions;
                if (perms && typeof perms.has === "function") {
                    return perms.has(P.STAFF_MANAGE);
                }
                if (Array.isArray(perms)) {
                    return perms.includes(P.STAFF_MANAGE);
                }
                return false;
            },
            priority: 50,
            meta: { autoGenerated: true, createdAt: new Date().toISOString() },
        },
        {
            effect: "deny",
            description: `[AUTO-GENERATED] deny fallback for ${permissionKey}`,
            condition: () => true,
            priority: 0,
            meta: { autoGenerated: true, createdAt: new Date().toISOString() },
        },
    ];
}

// ─── Detection + Sync ──────────────────────────────────────────────────────

/**
 * Detect missing policies and either auto-generate (warn) or crash (strict).
 *
 * @param {Object} [options]
 * @param {"warn"|"strict"} [options.mode="warn"]
 * @returns {{ synced: number, missing: string[] }}
 */
function autoSyncPolicies({ mode = "warn" } = {}) {
    const allPermissions = [...new Set(Object.values(P))];
    const existingKeys = new Set(Object.keys(policies));

    const missing = allPermissions.filter((p) => !existingKeys.has(p));

    if (missing.length === 0) {
        logger.info(
            { service: "PolicyAutoSync", total: allPermissions.length },
            `[PolicyAutoSync] ✅ All ${allPermissions.length} permissions have policies — zero drift.`
        );
        return { synced: 0, missing: [] };
    }

    // ── Strict mode → crash (production / CI) ──────────────────────────────
    if (mode === "strict") {
        const msg =
            `[PolicyAutoSync] ❌ Missing policies detected for ${missing.length} permission(s):\n` +
            missing.map((p) => `  - ${p}`).join("\n") +
            `\n\nDeploy blocked. Add policies to src/rbac/policies/ for each missing permission.`;

        logger.error({ service: "PolicyAutoSync", missing }, msg);
        throw new Error(msg);
    }

    // ── Warn mode → auto-generate safe defaults ────────────────────────────
    for (const permissionKey of missing) {
        policies[permissionKey] = generateDefaultPolicy(permissionKey);
    }

    logger.warn(
        { service: "PolicyAutoSync", synced: missing.length, missing },
        `[PolicyAutoSync] ⚠️ Auto-generated ${missing.length} default policies (org_admin only):\n` +
        missing.map((p) => `  - ${p}`).join("\n") +
        `\n\n→ Replace these with proper domain policies before deploying to production.`
    );

    return { synced: missing.length, missing };
}

module.exports = { autoSyncPolicies, generateDefaultPolicy };
