/**
 * permissionValidator.js — Frontend Permission Key Validator
 *
 * Validates that permission keys used in <Can>, useCapability(), and
 * other UI guards are valid SSOT-registered keys.
 *
 * In development: logs console.error for invalid keys (loud but non-breaking).
 * In production: silently returns (no console noise, no breakage).
 *
 * Source:
 *   Primary:  frontend/src/generated/permissionKeys.js  (PermissionSet — O(1))
 *   Fallback: frontend/src/generated/permissionKeys.json
 *
 * Generated by: npm run generate:permission-keys  (from backend/)
 *   or:         npm run sync:permissions
 *
 * PLANE: Org only.
 */

import { PermissionSet } from "@/generated/permissionKeys";

// PermissionSet is already a pre-built Set<string> — no re-construction needed.
const VALID_KEYS = PermissionSet;

const IS_DEV = process.env.NODE_ENV !== "production";

// Track already-warned keys to avoid console noise on re-renders
const warnedKeys = new Set();

/**
 * Validate that a permission key is a registered SSOT key.
 * In dev mode: logs a console.error on first occurrence.
 * In prod: silently skips.
 *
 * @param {string} key - Permission key (e.g., "patients.update")
 * @param {string} [source] - Caller info for debugging (e.g., "Can", "useCapability")
 * @returns {boolean} true if valid
 */
export function validatePermissionKey(key, source = "unknown") {
    if (!key || typeof key !== "string") {
        if (IS_DEV) {
            console.error(
                `🚨 [permissionValidator] Invalid permission key type: ${typeof key} (from ${source})`
            );
        }
        return false;
    }

    if (!VALID_KEYS.has(key)) {
        if (IS_DEV && !warnedKeys.has(key)) {
            warnedKeys.add(key);
            console.error(
                `🚨 [permissionValidator] INVALID PERMISSION KEY: "${key}" (from ${source}).\n` +
                `Valid keys (${VALID_KEYS.size}): ${[...VALID_KEYS].sort().join(", ")}`
            );
        }
        return false;
    }

    return true;
}

/**
 * Check if a permission key is valid (silent — no console output).
 *
 * @param {string} key - Permission key to check
 * @returns {boolean}
 */
export function isValidPermissionKey(key) {
    return typeof key === "string" && VALID_KEYS.has(key);
}

/**
 * Get all valid permission keys.
 * @returns {ReadonlySet<string>}
 */
export function getValidKeys() {
    return VALID_KEYS;
}
