/**
 * platformContract.cjs.js
 * v20.1 Wave3 — CommonJS version for backend — mirrors ESM contract exactly
 */

const PLATFORM_CAPABILITIES = {
    VIEW_ORGANIZATIONS: "VIEW_ORGANIZATIONS",
    MANAGE_ORGANIZATIONS: "MANAGE_ORGANIZATIONS",
    MANAGE_SUBSCRIPTIONS: "MANAGE_SUBSCRIPTIONS",
    VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
    VIEW_PLATFORM_ANALYTICS: "VIEW_PLATFORM_ANALYTICS",
    MANAGE_PLATFORM_USERS: "MANAGE_PLATFORM_USERS",
    MANAGE_PLATFORM_SETTINGS: "MANAGE_PLATFORM_SETTINGS",
    // v3.1 — Communication Infrastructure
    VIEW_COMMUNICATION_METRICS: "VIEW_COMMUNICATION_METRICS",
    MANAGE_COMMUNICATION: "MANAGE_COMMUNICATION",
};

const PLATFORM_ROLES = {
    superadmin: [
        PLATFORM_CAPABILITIES.VIEW_ORGANIZATIONS,
        PLATFORM_CAPABILITIES.MANAGE_ORGANIZATIONS,
        PLATFORM_CAPABILITIES.MANAGE_SUBSCRIPTIONS,
        PLATFORM_CAPABILITIES.VIEW_AUDIT_LOGS,
        PLATFORM_CAPABILITIES.VIEW_PLATFORM_ANALYTICS,
        PLATFORM_CAPABILITIES.MANAGE_PLATFORM_USERS,
        PLATFORM_CAPABILITIES.MANAGE_PLATFORM_SETTINGS,
        PLATFORM_CAPABILITIES.VIEW_COMMUNICATION_METRICS,
        PLATFORM_CAPABILITIES.MANAGE_COMMUNICATION,
    ],
    operations_admin: [
        PLATFORM_CAPABILITIES.VIEW_ORGANIZATIONS,
        PLATFORM_CAPABILITIES.VIEW_AUDIT_LOGS
    ],
    finance_admin: [
        PLATFORM_CAPABILITIES.VIEW_ORGANIZATIONS,
        PLATFORM_CAPABILITIES.MANAGE_SUBSCRIPTIONS,
        PLATFORM_CAPABILITIES.VIEW_PLATFORM_ANALYTICS
    ],
    analyst: [
        PLATFORM_CAPABILITIES.VIEW_ORGANIZATIONS,
        PLATFORM_CAPABILITIES.VIEW_AUDIT_LOGS,
        PLATFORM_CAPABILITIES.VIEW_PLATFORM_ANALYTICS
    ]
};


const PLATFORM_FEATURE_FLAGS = {
    ADVANCED_ANALYTICS: true,
    ENTERPRISE_REPORTING: true,
    SYSTEM_MONITOR: false,
    PLATFORM_KILL_SWITCH: false
};

module.exports = {
    PLATFORM_CAPABILITIES,
    PLATFORM_ROLES,
    PLATFORM_FEATURE_FLAGS
};
