/**
 * r2SignedUrl.service.js
 * Infrastructure — Cloudflare R2 Pre-Signed URL Service
 *
 * Generates time-limited, pre-signed GET URLs for private R2 objects.
 * This is the ONLY permitted access method — the bucket has no public access.
 *
 * SECURITY DECISIONS:
 *   - Org access control: every key MUST start with org_{orgId}/.
 *     When orgId is passed, the key prefix is validated before presigning.
 *     This prevents one org from signing URLs for another org's files even if
 *     a key is accidentally passed cross-tenant.
 *   - Signed URLs are per-object and time-limited. R2 enforces expiry server-side.
 *   - Raw keys are NEVER returned to the frontend — only signed URLs.
 *
 * PERFORMANCE:
 *   - Signed URLs are cached in-memory for SIGNED_URL_CACHE_TTL_MS (default 55s).
 *     This avoids redundant presign API calls for repeated access to the same file
 *     within a short window (e.g. a page rendering multiple attachments).
 *   - Cache is keyed by `${orgId}:${key}` to prevent cross-org cache collisions.
 *   - 55s is conservative relative to the default 3600s URL TTL — the cached URL
 *     is guaranteed to still be valid when served.
 *   - Cache entries are lazily evicted on access (no background sweep needed).
 *
 * PLANE: Infrastructure (cross-cutting)
 */

"use strict";

const { getR2Client, getBucket } = require("./r2Client");
const StorageError = require("./storageError");

// ─── Configuration ────────────────────────────────────────────────────────────

/**
 * Default signed URL TTL in seconds.
 * Override per-request via the expiresIn parameter.
 * Override globally via FILE_SIGNED_URL_TTL env variable.
 */
const DEFAULT_TTL = parseInt(process.env.FILE_SIGNED_URL_TTL, 10) || 3600;

/**
 * In-memory signed URL cache TTL in milliseconds.
 *
 * Set to 55s — safely below the minimum expected URL lifetime (3600s default).
 * Even if a caller uses expiresIn=60, the 55s cache margin leaves 5s of validity
 * at cache eviction. For short TTL use cases (< 60s), caching is automatically
 * skipped — see logic in getSignedFileUrl().
 */
const SIGNED_URL_CACHE_TTL_MS = 55_000;

// ─── In-Memory Signed URL Cache ───────────────────────────────────────────────

/**
 * Cache structure: Map<cacheKey, { url: string, expiresAt: number }>
 *
 * Cache key format: "${orgId}:${key}"
 *   - orgId scoping prevents cross-tenant cache hits
 *   - When orgId is not provided, key is used alone (less safe — avoid in prod)
 *
 * Entries are lazily evicted on read.
 */
const _urlCache = new Map();

function _buildCacheKey(key, orgId) {
    return orgId ? `${orgId}:${key}` : key;
}

function _getCachedUrl(key, orgId) {
    const cacheKey = _buildCacheKey(key, orgId);
    const entry = _urlCache.get(cacheKey);
    if (!entry) return null;

    // Lazy eviction: remove and return null if expired
    if (Date.now() >= entry.expiresAt) {
        _urlCache.delete(cacheKey);
        return null;
    }
    return entry.url;
}

function _setCachedUrl(key, orgId, url) {
    const cacheKey = _buildCacheKey(key, orgId);
    _urlCache.set(cacheKey, {
        url,
        expiresAt: Date.now() + SIGNED_URL_CACHE_TTL_MS,
    });
}

// ─── Logger ───────────────────────────────────────────────────────────────────

function _logger() {
    try { return require("@utils/logger"); } catch { return console; }
}

// ─── Org Access Control ───────────────────────────────────────────────────────

/**
 * Validate that a key belongs to the given organization.
 *
 * Keys generated by r2Upload.generateKey() always start with org_{orgId}/.
 * This check ensures the signed URL service cannot be used to generate
 * a valid presigned URL for a key belonging to a different org.
 *
 * @param {string} key   — R2 object key
 * @param {string} orgId — Expected organization ID
 * @throws {StorageError} UNAUTHORIZED_FILE_ACCESS if the prefix does not match
 */
function assertKeyOwnership(key, orgId) {
    const expectedPrefix = `org_${orgId}/`;
    if (!key.startsWith(expectedPrefix)) {
        throw new StorageError(
            "UNAUTHORIZED_FILE_ACCESS",
            "[r2SignedUrl] Key org prefix does not match caller's orgId",
            {
                // Do NOT include the full key — it may contain sensitive path segments
                keyPrefix: key.split("/")[0],
                expectedPrefix,
            }
        );
    }
}

// ─── Signed URL Generation ────────────────────────────────────────────────────

/**
 * Generate a pre-signed GET URL for a private R2 object.
 *
 * The URL grants time-limited, single-object read access.
 * It must be regenerated after expiry — do NOT persist signed URLs to the DB.
 *
 * When orgId is provided (strongly recommended), the key is validated to
 * ensure it belongs to that org before the URL is generated.
 *
 * SHORT TTL NOTE: If expiresIn < 60 seconds, the in-memory cache is bypassed
 * since the cache window (55s) would exceed the URL lifetime.
 *
 * @param {string} key              — R2 object key (stored as imageKey in DB)
 * @param {string} [orgId]          — Organization ID for ownership assertion
 * @param {number} [expiresIn]      — TTL in seconds (default: FILE_SIGNED_URL_TTL || 3600)
 * @returns {Promise<string>}       Signed URL
 * @throws {StorageError} UNAUTHORIZED_FILE_ACCESS — key prefix does not match orgId
 * @throws {StorageError} SIGNED_URL_FAILED        — presign API call failed
 */
async function getSignedFileUrl(key, orgId = null, expiresIn = DEFAULT_TTL) {
    if (!key) {
        throw new StorageError(
            "MISSING_UPLOAD_CONTEXT",
            "[r2SignedUrl] key is required to generate a signed URL",
            { orgId }
        );
    }

    const log = _logger();

    // ── Org access control (§1.3) ─────────────────────────────────────────────
    // Validate that the key belongs to the requesting org BEFORE presigning.
    // This is the primary cross-tenant isolation check for file access.
    if (orgId) {
        assertKeyOwnership(key, orgId);
    }

    // ── Cache hit ─────────────────────────────────────────────────────────────
    // Skip cache for short TTLs (< 60s) where the cached URL might outlive the URL.
    const useCache = expiresIn >= 60;
    if (useCache) {
        const cached = _getCachedUrl(key, orgId);
        if (cached) return cached;
    }

    // ── Generate signed URL ───────────────────────────────────────────────────
    try {
        const { GetObjectCommand }  = require("@aws-sdk/client-s3");
        const { getSignedUrl }      = require("@aws-sdk/s3-request-presigner");

        const client  = getR2Client();
        const bucket  = getBucket();

        const command = new GetObjectCommand({ Bucket: bucket, Key: key });
        const url = await getSignedUrl(client, command, { expiresIn });

        // ── Cache the URL ─────────────────────────────────────────────────────
        if (useCache) {
            _setCachedUrl(key, orgId, url);
        }

        // ── Audit log: FILE_ACCESS (§6.1) ─────────────────────────────────────
        log.info({
            event:     "FILE_ACCESS",
            orgId:     orgId || null,
            // Key segment only — do not log full key (contains orgId + path segments)
            keyPrefix: key.split("/").slice(0, 3).join("/"),
            expiresIn,
            cached:    false,
        }, "[r2SignedUrl] Signed URL generated");

        return url;

    } catch (err) {
        // Re-throw StorageErrors (e.g. UNAUTHORIZED_FILE_ACCESS from assertKeyOwnership)
        if (err.name === "StorageError") throw err;

        log.error({
            event:  "SIGNED_URL_FAILED",
            orgId:  orgId || null,
            err:    err.message,
        }, "[r2SignedUrl] Failed to generate signed URL");

        throw new StorageError(
            "SIGNED_URL_FAILED",
            `[r2SignedUrl] Failed to generate signed URL: ${err.message}`,
            { orgId, cause: err.message }
        );
    }
}

/**
 * Clear the in-memory URL cache — for testing only.
 * @private
 */
function _clearCache() {
    _urlCache.clear();
}

module.exports = {
    getSignedFileUrl,
    assertKeyOwnership,
    DEFAULT_TTL,
    SIGNED_URL_CACHE_TTL_MS,
    _clearCache,
};
