/**
 * SecurityAlert.js — Security Alert Model
 *
 * Stores security alerts generated by the alerting system.
 * Alerts are triggered by threshold-based rules and anomaly detection.
 *
 * Types:
 *   - HIGH_DENIAL_RATE      — Spike in denied access attempts
 *   - SUSPICIOUS_ACCESS     — Unusual access patterns (rapid patient access, cross-branch)
 *   - BRUTE_FORCE_ATTEMPT   — Too many failed requests from single user
 *   - PRIVILEGE_ESCALATION  — Repeated attempts to access admin-only resources
 *   - POLICY_VIOLATION      — Repeated policy evaluation failures
 *
 * PLANE: Org only — scoped by organizationId.
 * COLLECTION: securityalerts
 */

"use strict";

const mongoose = require("mongoose");
const ALERT_TYPES = ["HIGH_DENIAL_RATE", "SUSPICIOUS_ACCESS", "BRUTE_FORCE_ATTEMPT", "PRIVILEGE_ESCALATION", "POLICY_VIOLATION"];
const ALERT_SEVERITIES = ["LOW", "MEDIUM", "HIGH", "CRITICAL"];
const ALERT_STATUSES = ["active", "acknowledged", "resolved"];
const securityAlertSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ALERT_TYPES,
    required: true
  },
  severity: {
    type: String,
    enum: ALERT_SEVERITIES,
    required: true
  },
  status: {
    type: String,
    enum: ALERT_STATUSES,
    default: "active"
  },
  message: {
    type: String,
    required: true
  },
  details: {
    type: mongoose.Schema.Types.Mixed,
    default: {}
  },
  // The user who triggered the alert (if applicable)
  triggeredByUserId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    default: null
  },
  // The user who acknowledged the alert
  acknowledgedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    default: null
  },
  acknowledgedAt: {
    type: Date,
    default: null
  },
  // The user who resolved the alert
  resolvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    default: null
  },
  resolvedAt: {
    type: Date,
    default: null
  },
  // Deduplication: window key to prevent flood of identical alerts
  deduplicationKey: {
    type: String,
    default: null
  }
}, {
  timestamps: true
});

// ─── Indexes ────────────────────────────────────────────────────────────────

securityAlertSchema.index({
  createdAt: -1
});
securityAlertSchema.index({
  status: 1
});
securityAlertSchema.index({
  type: 1,
  createdAt: -1
});
securityAlertSchema.index({
  severity: 1,
  status: 1
});
securityAlertSchema.index({
  deduplicationKey: 1
}, {
  sparse: true,
  unique: true
});
const modelName = "SecurityAlert";
module.exports = {
  modelName,
  schema: securityAlertSchema,
  default: mongoose.models[modelName] || mongoose.model(modelName, securityAlertSchema)
};
module.exports.ALERT_TYPES = ALERT_TYPES;
module.exports.ALERT_SEVERITIES = ALERT_SEVERITIES;
module.exports.ALERT_STATUSES = ALERT_STATUSES;