/**
 * generateCapabilities.js — Capability Contract Generator
 *
 * Fetches the full SSOT permission key list from the backend
 * (GET /org/me/permission-keys → orgPermissions.js P enum)
 * and writes src/generated/capabilities.js.
 *
 * Output: a frozen CAP object with typed constants:
 *   CAP.PATIENTS.READ   → "patients.read"
 *   CAP.INVENTORY.READ  → "inventory.read"
 *
 * IMPORTANT: This script must be run against a RUNNING backend.
 * The backend URL is resolved from VITE_API_URL in .env, or
 * defaults to http://localhost:5000.
 *
 * Usage:
 *   node scripts/generateCapabilities.js
 *   npm run generate:capabilities
 *
 * CI usage (requires backend to be running):
 *   npm run generate:capabilities && git diff --exit-code src/generated/
 */

import { writeFileSync, mkdirSync, existsSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ─── Config ─────────────────────────────────────────────────────────────────
// Reads VITE_API_URL from env, falls back to localhost.
// The /org/me/permission-keys endpoint requires an org JWT.
// For CI/generation purposes, a special no-auth static export is preferred.
// See: backend GET /org/me/permission-keys (added in PERMISSION-DRIFT-ENGINE v1.0)
const BASE_URL = process.env.VITE_API_URL || "http://localhost:5000";
const ENDPOINT = `${BASE_URL}/api/v1/org/me/permission-keys`;
const OUT_DIR  = resolve(__dirname, "../src/generated");
const OUT_FILE = resolve(OUT_DIR, "capabilities.js");

// ─── Token from env for CI use ──────────────────────────────────────────────
// In CI, set GENERATE_CAP_TOKEN=<org_jwt> to authenticate the request.
const token = process.env.GENERATE_CAP_TOKEN || "";

// ─── Fetch ──────────────────────────────────────────────────────────────────
async function fetchPermissionKeys() {
    const headers = { "Content-Type": "application/json" };
    if (token) headers["Authorization"] = `Bearer ${token}`;

    const response = await fetch(ENDPOINT, { headers });

    if (!response.ok) {
        throw new Error(
            `[generateCapabilities] Backend returned ${response.status} from ${ENDPOINT}.\n` +
            `Make sure the backend is running and GENERATE_CAP_TOKEN is set if auth is required.`
        );
    }

    const body = await response.json();

    // Backend returns { data: { keys: string[], count: number }, ... }
    // or { data: string[] } depending on successResponse shape
    const keys = body?.data?.keys ?? body?.data ?? body?.keys ?? body;

    if (!Array.isArray(keys) || keys.length === 0) {
        throw new Error(`[generateCapabilities] Unexpected response shape: ${JSON.stringify(body)}`);
    }

    return keys;
}

// ─── Generate ────────────────────────────────────────────────────────────────
function generateOutput(keys) {
    // Group by domain
    const groups = {};
    for (const key of keys.sort()) {
        const dot = key.indexOf(".");
        if (dot === -1) continue;
        const domain = key.substring(0, dot);
        const action = key.substring(dot + 1);
        if (!groups[domain]) groups[domain] = [];
        if (!groups[domain].includes(action)) groups[domain].push(action);
    }

    const header = `/**
 * capabilities.js — AUTO-GENERATED CAPABILITY CONSTANTS
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY.
 *     Generated by: npm run generate:capabilities
 *     Source:       orgPermissions.js (P enum) via GET /org/me/permission-keys
 *
 * Generated: ${new Date().toISOString()}
 * Keys:      ${keys.length}
 *
 * Usage:
 *   import { CAP } from "@/generated/capabilities";
 *   usePermission(CAP.PATIENTS.READ);    // ✅ correct
 *   usePermission("patients.read");      // ❌ raw string — forbidden
 */

// eslint-disable-next-line
/* AUTO-GENERATED — DO NOT EDIT */\n\n`;

    let body = "export const CAP = Object.freeze({\n";

    for (const [domain, actions] of Object.entries(groups).sort()) {
        const domainConst = domain.toUpperCase().replace(/[^A-Z0-9]/g, "_");
        body += `    ${domainConst}: Object.freeze({\n`;
        for (const action of actions.sort()) {
            const actionConst = action.toUpperCase().replace(/[^A-Z0-9]/g, "_");
            body += `        ${actionConst}: "${domain}.${action}",\n`;
        }
        body += `    }),\n`;
    }

    body += `});\n\n`;

    // Flat set for runtime validation
    body += `/**\n * ALL_CAPS — flat Set of all valid capability strings.\n * Used by usePermission for dev-mode validation.\n */\n`;
    body += `export const ALL_CAPS = Object.freeze(\n    new Set([\n`;
    for (const key of keys.sort()) {
        body += `        "${key}",\n`;
    }
    body += `    ])\n);\n`;

    return header + body;
}

// ─── Write ───────────────────────────────────────────────────────────────────
async function main() {
    console.log(`[generateCapabilities] Fetching from ${ENDPOINT}...`);

    const keys = await fetchPermissionKeys();
    console.log(`[generateCapabilities] Received ${keys.length} permission keys.`);

    const output = generateOutput(keys);

    if (!existsSync(OUT_DIR)) {
        mkdirSync(OUT_DIR, { recursive: true });
    }

    writeFileSync(OUT_FILE, output, "utf8");
    console.log(`[generateCapabilities] ✅ Written to ${OUT_FILE}`);
    console.log(`[generateCapabilities] Run 'git diff src/generated/' to review changes.`);
}

main().catch((err) => {
    console.error(err.message);
    process.exit(1);
});
