/**
 * rolePermissions.test.js — AUTO-GENERATED
 *
 * ⚠️  DO NOT EDIT THIS FILE BY HAND.
 *     Regenerate via: node backend/scripts/generateRoleTests.js
 *
 * Generated at:        2026-04-18T20:52:22.609Z
 * PERMISSION_VERSION:  9
 *
 * What this suite proves:
 *   For every system role in ORG_ROLES, the full RBAC pipeline
 *     ORG_ROLE_PERMISSIONS → generateRoleSeed → resolvePermissionSet
 *                         → resolveAuthority → effective permissions
 *   produces EXACTLY the permissions baked into the SSOT at generation time.
 *
 * If this suite fails after a SSOT change, regenerate it and review the diff
 * before committing — a role's effective grants should only change with intent.
 */

"use strict";

const {
    ORG_ROLE_PERMISSIONS,
} = require("../src/rbac/orgPermissions");
const {
    generateRoleSeed,
    flattenPermissions,
} = require("../src/rbac/permissionRegistry");
const { resolvePermissionSet } = require("../src/rbac/accessResolver");
const { resolveAuthority } = require("../src/core/security/authorityBridge");

function effectiveForRole(role) {
    const nested = generateRoleSeed(role);
    const orgSet = resolvePermissionSet({ rolePermissions: nested, planModules: undefined });
    const authority = resolveAuthority({
        orgPermissionSet: orgSet,
        platformDesignation: null,
    });
    return {
        nestedFlat: [...flattenPermissions(nested)].sort(),
        resolved: [...authority.effectivePermissions].sort(),
    };
}

describe("RBAC pipeline — role \"org_admin\"", () => {
    it("org_admin baseline matches ORG_ROLE_PERMISSIONS SSOT", () => {
        const baseline = [...(ORG_ROLE_PERMISSIONS["org_admin"] || [])].sort();
        expect(baseline).toEqual(["accounting.create","accounting.delete","accounting.manage","accounting.read","accounting.reports","accounting.update","analytics.export","analytics.read","appointments.create","appointments.delete","appointments.read","appointments.update","billing.read","branches.create","branches.delete","branches.read","branches.update","calendar.multiBranchView","calendar.read","communication.manage","communication.read","communication.send","dashboard.manage","dashboard.read","documents.create","documents.manage","documents.read","families.create","families.delete","families.read","families.update","inventory.create","inventory.delete","inventory.read","inventory.update","invoices.create","invoices.delete","invoices.read","invoices.update","lab.create","lab.delete","lab.read","lab.update","ledger.read","monitoring.review","orthodontics.full","patients.create","patients.delete","patients.read","patients.update","payments.create","payments.delete","payments.read","payments.update","portal.manage","portal.read","procedures.create","procedures.delete","procedures.read","procedures.update","recalls.create","recalls.delete","recalls.read","recalls.update","refunds.create","refunds.read","security.manage","security.read","staff.manage","storage.read","support.create","support.read","support.write","treatments.create","treatments.delete","treatments.read","treatments.update","users.create","users.delete","users.read","users.update"]);
    });

    it("org_admin nested→flat matches expected", () => {
        const { nestedFlat } = effectiveForRole("org_admin");
        expect(nestedFlat).toEqual(["accounting.create","accounting.delete","accounting.manage","accounting.read","accounting.reports","accounting.update","analytics.export","analytics.read","appointments.create","appointments.delete","appointments.read","appointments.update","billing.read","branches.create","branches.delete","branches.read","branches.update","calendar.multiBranchView","calendar.read","communication.manage","communication.read","communication.send","dashboard.manage","dashboard.read","documents.create","documents.manage","documents.read","families.create","families.delete","families.read","families.update","inventory.create","inventory.delete","inventory.read","inventory.update","invoices.create","invoices.delete","invoices.read","invoices.update","lab.create","lab.delete","lab.read","lab.update","ledger.read","monitoring.review","orthodontics.full","patients.create","patients.delete","patients.read","patients.update","payments.create","payments.delete","payments.read","payments.update","portal.manage","portal.read","procedures.create","procedures.delete","procedures.read","procedures.update","recalls.create","recalls.delete","recalls.read","recalls.update","refunds.create","refunds.read","security.manage","security.read","staff.manage","storage.read","support.create","support.read","support.write","treatments.create","treatments.delete","treatments.read","treatments.update","users.create","users.delete","users.read","users.update"]);
    });

    it("org_admin resolved pipeline matches expected", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toEqual(["accounting.create","accounting.delete","accounting.manage","accounting.read","accounting.reports","accounting.update","analytics.export","analytics.read","appointments.create","appointments.delete","appointments.read","appointments.update","billing.read","branches.create","branches.delete","branches.read","branches.update","calendar.multiBranchView","calendar.read","communication.manage","communication.read","communication.send","dashboard.manage","dashboard.read","documents.create","documents.manage","documents.read","families.create","families.delete","families.read","families.update","inventory.create","inventory.delete","inventory.read","inventory.update","invoices.create","invoices.delete","invoices.read","invoices.update","lab.create","lab.delete","lab.read","lab.update","ledger.read","monitoring.review","orthodontics.full","patients.create","patients.delete","patients.read","patients.update","payments.create","payments.delete","payments.read","payments.update","portal.manage","portal.read","procedures.create","procedures.delete","procedures.read","procedures.update","recalls.create","recalls.delete","recalls.read","recalls.update","refunds.create","refunds.read","security.manage","security.read","staff.manage","storage.read","support.create","support.read","support.write","treatments.create","treatments.delete","treatments.read","treatments.update","users.create","users.delete","users.read","users.update"]);
    });

    it("org_admin should resolve \"accounting.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("accounting.create");
    });
    it("org_admin should resolve \"accounting.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("accounting.delete");
    });
    it("org_admin should resolve \"accounting.manage\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("accounting.manage");
    });
    it("org_admin should resolve \"accounting.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("accounting.read");
    });
    it("org_admin should resolve \"accounting.reports\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("accounting.reports");
    });
    it("org_admin should resolve \"accounting.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("accounting.update");
    });
    it("org_admin should resolve \"analytics.export\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("analytics.export");
    });
    it("org_admin should resolve \"analytics.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("analytics.read");
    });
    it("org_admin should resolve \"appointments.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("appointments.create");
    });
    it("org_admin should resolve \"appointments.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("appointments.delete");
    });
    it("org_admin should resolve \"appointments.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("appointments.read");
    });
    it("org_admin should resolve \"appointments.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("appointments.update");
    });
    it("org_admin should resolve \"billing.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("billing.read");
    });
    it("org_admin should resolve \"branches.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("branches.create");
    });
    it("org_admin should resolve \"branches.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("branches.delete");
    });
    it("org_admin should resolve \"branches.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("branches.read");
    });
    it("org_admin should resolve \"branches.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("branches.update");
    });
    it("org_admin should resolve \"calendar.multiBranchView\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("calendar.multiBranchView");
    });
    it("org_admin should resolve \"calendar.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("calendar.read");
    });
    it("org_admin should resolve \"communication.manage\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("communication.manage");
    });
    it("org_admin should resolve \"communication.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("communication.read");
    });
    it("org_admin should resolve \"communication.send\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("communication.send");
    });
    it("org_admin should resolve \"dashboard.manage\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("dashboard.manage");
    });
    it("org_admin should resolve \"dashboard.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("dashboard.read");
    });
    it("org_admin should resolve \"documents.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("documents.create");
    });
    it("org_admin should resolve \"documents.manage\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("documents.manage");
    });
    it("org_admin should resolve \"documents.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("documents.read");
    });
    it("org_admin should resolve \"families.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("families.create");
    });
    it("org_admin should resolve \"families.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("families.delete");
    });
    it("org_admin should resolve \"families.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("families.read");
    });
    it("org_admin should resolve \"families.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("families.update");
    });
    it("org_admin should resolve \"inventory.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("inventory.create");
    });
    it("org_admin should resolve \"inventory.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("inventory.delete");
    });
    it("org_admin should resolve \"inventory.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("inventory.read");
    });
    it("org_admin should resolve \"inventory.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("inventory.update");
    });
    it("org_admin should resolve \"invoices.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("invoices.create");
    });
    it("org_admin should resolve \"invoices.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("invoices.delete");
    });
    it("org_admin should resolve \"invoices.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("invoices.read");
    });
    it("org_admin should resolve \"invoices.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("invoices.update");
    });
    it("org_admin should resolve \"lab.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("lab.create");
    });
    it("org_admin should resolve \"lab.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("lab.delete");
    });
    it("org_admin should resolve \"lab.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("lab.read");
    });
    it("org_admin should resolve \"lab.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("lab.update");
    });
    it("org_admin should resolve \"ledger.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("ledger.read");
    });
    it("org_admin should resolve \"monitoring.review\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("monitoring.review");
    });
    it("org_admin should resolve \"orthodontics.full\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("orthodontics.full");
    });
    it("org_admin should resolve \"patients.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("patients.create");
    });
    it("org_admin should resolve \"patients.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("patients.delete");
    });
    it("org_admin should resolve \"patients.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("patients.read");
    });
    it("org_admin should resolve \"patients.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("patients.update");
    });
    it("org_admin should resolve \"payments.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("payments.create");
    });
    it("org_admin should resolve \"payments.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("payments.delete");
    });
    it("org_admin should resolve \"payments.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("payments.read");
    });
    it("org_admin should resolve \"payments.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("payments.update");
    });
    it("org_admin should resolve \"portal.manage\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("portal.manage");
    });
    it("org_admin should resolve \"portal.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("portal.read");
    });
    it("org_admin should resolve \"procedures.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("procedures.create");
    });
    it("org_admin should resolve \"procedures.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("procedures.delete");
    });
    it("org_admin should resolve \"procedures.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("procedures.read");
    });
    it("org_admin should resolve \"procedures.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("procedures.update");
    });
    it("org_admin should resolve \"recalls.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("recalls.create");
    });
    it("org_admin should resolve \"recalls.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("recalls.delete");
    });
    it("org_admin should resolve \"recalls.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("recalls.read");
    });
    it("org_admin should resolve \"recalls.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("recalls.update");
    });
    it("org_admin should resolve \"refunds.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("refunds.create");
    });
    it("org_admin should resolve \"refunds.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("refunds.read");
    });
    it("org_admin should resolve \"security.manage\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("security.manage");
    });
    it("org_admin should resolve \"security.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("security.read");
    });
    it("org_admin should resolve \"staff.manage\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("staff.manage");
    });
    it("org_admin should resolve \"storage.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("storage.read");
    });
    it("org_admin should resolve \"support.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("support.create");
    });
    it("org_admin should resolve \"support.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("support.read");
    });
    it("org_admin should resolve \"support.write\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("support.write");
    });
    it("org_admin should resolve \"treatments.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("treatments.create");
    });
    it("org_admin should resolve \"treatments.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("treatments.delete");
    });
    it("org_admin should resolve \"treatments.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("treatments.read");
    });
    it("org_admin should resolve \"treatments.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("treatments.update");
    });
    it("org_admin should resolve \"users.create\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("users.create");
    });
    it("org_admin should resolve \"users.delete\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("users.delete");
    });
    it("org_admin should resolve \"users.read\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("users.read");
    });
    it("org_admin should resolve \"users.update\"", () => {
        const { resolved } = effectiveForRole("org_admin");
        expect(resolved).toContain("users.update");
    });
});

describe("RBAC pipeline — role \"doctor\"", () => {
    it("doctor baseline matches ORG_ROLE_PERMISSIONS SSOT", () => {
        const baseline = [...(ORG_ROLE_PERMISSIONS["doctor"] || [])].sort();
        expect(baseline).toEqual(["accounting.read","analytics.read","appointments.create","appointments.read","appointments.update","branches.read","calendar.read","calendar.selfFilterOnly","communication.read","communication.send","dashboard.read","documents.create","documents.read","families.create","families.read","inventory.read","invoices.create","invoices.read","lab.create","lab.read","monitoring.review","orthodontics.full","patients.create","patients.read","patients.update","payments.read","portal.read","procedures.create","procedures.read","procedures.update","recalls.create","recalls.read","storage.read","support.create","support.read","support.write","treatments.create","treatments.read","treatments.update"]);
    });

    it("doctor nested→flat matches expected", () => {
        const { nestedFlat } = effectiveForRole("doctor");
        expect(nestedFlat).toEqual(["accounting.read","analytics.read","appointments.create","appointments.read","appointments.update","branches.read","calendar.read","calendar.selfFilterOnly","communication.read","communication.send","dashboard.read","documents.create","documents.read","families.create","families.read","inventory.read","invoices.create","invoices.read","lab.create","lab.read","monitoring.review","orthodontics.full","patients.create","patients.read","patients.update","payments.read","portal.read","procedures.create","procedures.read","procedures.update","recalls.create","recalls.read","storage.read","support.create","support.read","support.write","treatments.create","treatments.read","treatments.update"]);
    });

    it("doctor resolved pipeline matches expected", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toEqual(["accounting.read","analytics.read","appointments.create","appointments.read","appointments.update","branches.read","calendar.read","calendar.selfFilterOnly","communication.read","communication.send","dashboard.read","documents.create","documents.read","families.create","families.read","inventory.read","invoices.create","invoices.read","lab.create","lab.read","monitoring.review","orthodontics.full","patients.create","patients.read","patients.update","payments.read","portal.read","procedures.create","procedures.read","procedures.update","recalls.create","recalls.read","storage.read","support.create","support.read","support.write","treatments.create","treatments.read","treatments.update"]);
    });

    it("doctor should resolve \"accounting.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("accounting.read");
    });
    it("doctor should resolve \"analytics.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("analytics.read");
    });
    it("doctor should resolve \"appointments.create\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("appointments.create");
    });
    it("doctor should resolve \"appointments.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("appointments.read");
    });
    it("doctor should resolve \"appointments.update\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("appointments.update");
    });
    it("doctor should resolve \"branches.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("branches.read");
    });
    it("doctor should resolve \"calendar.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("calendar.read");
    });
    it("doctor should resolve \"calendar.selfFilterOnly\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("calendar.selfFilterOnly");
    });
    it("doctor should resolve \"communication.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("communication.read");
    });
    it("doctor should resolve \"communication.send\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("communication.send");
    });
    it("doctor should resolve \"dashboard.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("dashboard.read");
    });
    it("doctor should resolve \"documents.create\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("documents.create");
    });
    it("doctor should resolve \"documents.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("documents.read");
    });
    it("doctor should resolve \"families.create\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("families.create");
    });
    it("doctor should resolve \"families.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("families.read");
    });
    it("doctor should resolve \"inventory.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("inventory.read");
    });
    it("doctor should resolve \"invoices.create\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("invoices.create");
    });
    it("doctor should resolve \"invoices.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("invoices.read");
    });
    it("doctor should resolve \"lab.create\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("lab.create");
    });
    it("doctor should resolve \"lab.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("lab.read");
    });
    it("doctor should resolve \"monitoring.review\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("monitoring.review");
    });
    it("doctor should resolve \"orthodontics.full\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("orthodontics.full");
    });
    it("doctor should resolve \"patients.create\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("patients.create");
    });
    it("doctor should resolve \"patients.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("patients.read");
    });
    it("doctor should resolve \"patients.update\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("patients.update");
    });
    it("doctor should resolve \"payments.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("payments.read");
    });
    it("doctor should resolve \"portal.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("portal.read");
    });
    it("doctor should resolve \"procedures.create\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("procedures.create");
    });
    it("doctor should resolve \"procedures.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("procedures.read");
    });
    it("doctor should resolve \"procedures.update\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("procedures.update");
    });
    it("doctor should resolve \"recalls.create\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("recalls.create");
    });
    it("doctor should resolve \"recalls.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("recalls.read");
    });
    it("doctor should resolve \"storage.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("storage.read");
    });
    it("doctor should resolve \"support.create\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("support.create");
    });
    it("doctor should resolve \"support.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("support.read");
    });
    it("doctor should resolve \"support.write\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("support.write");
    });
    it("doctor should resolve \"treatments.create\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("treatments.create");
    });
    it("doctor should resolve \"treatments.read\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("treatments.read");
    });
    it("doctor should resolve \"treatments.update\"", () => {
        const { resolved } = effectiveForRole("doctor");
        expect(resolved).toContain("treatments.update");
    });
});

describe("RBAC pipeline — role \"assistant\"", () => {
    it("assistant baseline matches ORG_ROLE_PERMISSIONS SSOT", () => {
        const baseline = [...(ORG_ROLE_PERMISSIONS["assistant"] || [])].sort();
        expect(baseline).toEqual(["appointments.create","appointments.read","appointments.update","branches.read","calendar.read","communication.read","dashboard.read","documents.read","families.read","inventory.read","invoices.create","invoices.read","invoices.update","lab.read","orthodontics.read","patients.read","payments.read","portal.read","procedures.read","recalls.read","storage.read","support.create","support.read","treatments.read"]);
    });

    it("assistant nested→flat matches expected", () => {
        const { nestedFlat } = effectiveForRole("assistant");
        expect(nestedFlat).toEqual(["appointments.create","appointments.read","appointments.update","branches.read","calendar.read","communication.read","dashboard.read","documents.read","families.read","inventory.read","invoices.create","invoices.read","invoices.update","lab.read","orthodontics.read","patients.read","payments.read","portal.read","procedures.read","recalls.read","storage.read","support.create","support.read","treatments.read"]);
    });

    it("assistant resolved pipeline matches expected", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toEqual(["appointments.create","appointments.read","appointments.update","branches.read","calendar.read","communication.read","dashboard.read","documents.read","families.read","inventory.read","invoices.create","invoices.read","invoices.update","lab.read","orthodontics.read","patients.read","payments.read","portal.read","procedures.read","recalls.read","storage.read","support.create","support.read","treatments.read"]);
    });

    it("assistant should resolve \"appointments.create\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("appointments.create");
    });
    it("assistant should resolve \"appointments.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("appointments.read");
    });
    it("assistant should resolve \"appointments.update\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("appointments.update");
    });
    it("assistant should resolve \"branches.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("branches.read");
    });
    it("assistant should resolve \"calendar.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("calendar.read");
    });
    it("assistant should resolve \"communication.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("communication.read");
    });
    it("assistant should resolve \"dashboard.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("dashboard.read");
    });
    it("assistant should resolve \"documents.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("documents.read");
    });
    it("assistant should resolve \"families.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("families.read");
    });
    it("assistant should resolve \"inventory.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("inventory.read");
    });
    it("assistant should resolve \"invoices.create\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("invoices.create");
    });
    it("assistant should resolve \"invoices.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("invoices.read");
    });
    it("assistant should resolve \"invoices.update\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("invoices.update");
    });
    it("assistant should resolve \"lab.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("lab.read");
    });
    it("assistant should resolve \"orthodontics.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("orthodontics.read");
    });
    it("assistant should resolve \"patients.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("patients.read");
    });
    it("assistant should resolve \"payments.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("payments.read");
    });
    it("assistant should resolve \"portal.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("portal.read");
    });
    it("assistant should resolve \"procedures.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("procedures.read");
    });
    it("assistant should resolve \"recalls.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("recalls.read");
    });
    it("assistant should resolve \"storage.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("storage.read");
    });
    it("assistant should resolve \"support.create\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("support.create");
    });
    it("assistant should resolve \"support.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("support.read");
    });
    it("assistant should resolve \"treatments.read\"", () => {
        const { resolved } = effectiveForRole("assistant");
        expect(resolved).toContain("treatments.read");
    });
});

describe("RBAC pipeline — role \"receptionist\"", () => {
    it("receptionist baseline matches ORG_ROLE_PERMISSIONS SSOT", () => {
        const baseline = [...(ORG_ROLE_PERMISSIONS["receptionist"] || [])].sort();
        expect(baseline).toEqual(["accounting.read","appointments.create","appointments.read","appointments.update","branches.read","calendar.read","communication.read","communication.send","dashboard.read","families.create","families.read","families.update","inventory.read","invoices.create","invoices.read","patients.create","patients.read","payments.create","payments.read","portal.read","procedures.read","recalls.create","recalls.read","recalls.update","storage.read","support.create","support.read","treatments.read"]);
    });

    it("receptionist nested→flat matches expected", () => {
        const { nestedFlat } = effectiveForRole("receptionist");
        expect(nestedFlat).toEqual(["accounting.read","appointments.create","appointments.read","appointments.update","branches.read","calendar.read","communication.read","communication.send","dashboard.read","families.create","families.read","families.update","inventory.read","invoices.create","invoices.read","patients.create","patients.read","payments.create","payments.read","portal.read","procedures.read","recalls.create","recalls.read","recalls.update","storage.read","support.create","support.read","treatments.read"]);
    });

    it("receptionist resolved pipeline matches expected", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toEqual(["accounting.read","appointments.create","appointments.read","appointments.update","branches.read","calendar.read","communication.read","communication.send","dashboard.read","families.create","families.read","families.update","inventory.read","invoices.create","invoices.read","patients.create","patients.read","payments.create","payments.read","portal.read","procedures.read","recalls.create","recalls.read","recalls.update","storage.read","support.create","support.read","treatments.read"]);
    });

    it("receptionist should resolve \"accounting.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("accounting.read");
    });
    it("receptionist should resolve \"appointments.create\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("appointments.create");
    });
    it("receptionist should resolve \"appointments.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("appointments.read");
    });
    it("receptionist should resolve \"appointments.update\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("appointments.update");
    });
    it("receptionist should resolve \"branches.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("branches.read");
    });
    it("receptionist should resolve \"calendar.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("calendar.read");
    });
    it("receptionist should resolve \"communication.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("communication.read");
    });
    it("receptionist should resolve \"communication.send\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("communication.send");
    });
    it("receptionist should resolve \"dashboard.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("dashboard.read");
    });
    it("receptionist should resolve \"families.create\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("families.create");
    });
    it("receptionist should resolve \"families.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("families.read");
    });
    it("receptionist should resolve \"families.update\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("families.update");
    });
    it("receptionist should resolve \"inventory.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("inventory.read");
    });
    it("receptionist should resolve \"invoices.create\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("invoices.create");
    });
    it("receptionist should resolve \"invoices.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("invoices.read");
    });
    it("receptionist should resolve \"patients.create\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("patients.create");
    });
    it("receptionist should resolve \"patients.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("patients.read");
    });
    it("receptionist should resolve \"payments.create\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("payments.create");
    });
    it("receptionist should resolve \"payments.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("payments.read");
    });
    it("receptionist should resolve \"portal.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("portal.read");
    });
    it("receptionist should resolve \"procedures.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("procedures.read");
    });
    it("receptionist should resolve \"recalls.create\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("recalls.create");
    });
    it("receptionist should resolve \"recalls.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("recalls.read");
    });
    it("receptionist should resolve \"recalls.update\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("recalls.update");
    });
    it("receptionist should resolve \"storage.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("storage.read");
    });
    it("receptionist should resolve \"support.create\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("support.create");
    });
    it("receptionist should resolve \"support.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("support.read");
    });
    it("receptionist should resolve \"treatments.read\"", () => {
        const { resolved } = effectiveForRole("receptionist");
        expect(resolved).toContain("treatments.read");
    });
});

describe("RBAC pipeline — role \"lab_technician\"", () => {
    it("lab_technician baseline matches ORG_ROLE_PERMISSIONS SSOT", () => {
        const baseline = [...(ORG_ROLE_PERMISSIONS["lab_technician"] || [])].sort();
        expect(baseline).toEqual(["branches.read","calendar.read","dashboard.read","lab.create","lab.delete","lab.read","lab.update","orthodontics.read","patients.read","storage.read"]);
    });

    it("lab_technician nested→flat matches expected", () => {
        const { nestedFlat } = effectiveForRole("lab_technician");
        expect(nestedFlat).toEqual(["branches.read","calendar.read","dashboard.read","lab.create","lab.delete","lab.read","lab.update","orthodontics.read","patients.read","storage.read"]);
    });

    it("lab_technician resolved pipeline matches expected", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toEqual(["branches.read","calendar.read","dashboard.read","lab.create","lab.delete","lab.read","lab.update","orthodontics.read","patients.read","storage.read"]);
    });

    it("lab_technician should resolve \"branches.read\"", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toContain("branches.read");
    });
    it("lab_technician should resolve \"calendar.read\"", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toContain("calendar.read");
    });
    it("lab_technician should resolve \"dashboard.read\"", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toContain("dashboard.read");
    });
    it("lab_technician should resolve \"lab.create\"", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toContain("lab.create");
    });
    it("lab_technician should resolve \"lab.delete\"", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toContain("lab.delete");
    });
    it("lab_technician should resolve \"lab.read\"", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toContain("lab.read");
    });
    it("lab_technician should resolve \"lab.update\"", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toContain("lab.update");
    });
    it("lab_technician should resolve \"orthodontics.read\"", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toContain("orthodontics.read");
    });
    it("lab_technician should resolve \"patients.read\"", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toContain("patients.read");
    });
    it("lab_technician should resolve \"storage.read\"", () => {
        const { resolved } = effectiveForRole("lab_technician");
        expect(resolved).toContain("storage.read");
    });
});
