/**
 * ShareLink.model.js — Platform-Plane Public Share-Link Registry
 *
 * ROLE
 *   Token-gated, time-bound, read-only handle to a stored tenant asset (photo,
 *   case, etc.). Consumed by GET /api/v1/public/share-links/:token (no auth).
 *
 * PLANE: Platform
 *   Public routes have no authenticated context — the token IS the capability.
 *   To resolve token → org → cluster → tenant DB, the resolver needs a
 *   cross-tenant lookup. Per-org-DB isolation makes that impossible at the
 *   tenant plane (there's no way to know which DB to query without the token
 *   record first telling us). Therefore ShareLink lives on the platform
 *   cluster where a single indexed lookup on `token` resolves to an org id.
 *
 * BINDING
 *   Never compiled via `mongoose.model(...)` globally. Consumers use
 *   getShareLinkModel() which binds to platformConnection.
 *
 * SECURITY
 *   - `token` is the ONLY secret on the wire; kept in the URL only.
 *   - Expiry enforced via TTL index AND explicit controller check (410).
 *   - Token length / entropy validated at the controller boundary.
 *
 * Step 5c Commit 4 — this replaces src/modules/share/models/ShareLink.model.js
 * (tenant-plane variant, now deleted). orgId lives here as a first-class ref
 * because it IS the routing key from public token → cluster.
 */

"use strict";

const { Schema, Types } = require("mongoose");

const ShareLinkSchema = new Schema(
    {
        // Opaque token — cryptographically random, generated by the creating
        // authenticated endpoint. Unique across the entire platform (one
        // collection, one URL-space).
        token: {
            type: String,
            required: true,
            unique: true,
            index: true,
        },

        // Which tenant cluster + org DB the resource belongs to. Routing
        // flow: platform ShareLink → orgId → clusterRegistry → tenant DB.
        orgId: {
            type: Types.ObjectId,
            ref: "Organization",
            required: true,
            index: true,
        },

        resourceType: {
            type: String,
            enum: ["CASE", "FILE", "SNAPSHOT", "photo"],    // "photo" retained for legacy parity
            required: true,
        },

        resourceId: {
            type: Types.ObjectId,
            required: true,
        },

        permissions: {
            read:  { type: Boolean, default: true  },
            write: { type: Boolean, default: false },
        },

        // Legacy field name preserved for controller compatibility.
        permission: {
            type: String,
            enum: ["view", "download"],
            default: "view",
        },

        expiresAt: {
            type: Date,
            required: true,
            // TTL: Mongo physically removes expired docs on the next sweep.
            // Controller also returns 410 before the sweep for immediate UX.
            index: { expires: 0 },
        },

        createdBy: {
            type: Types.ObjectId,
            ref: "User",
            default: null,
        },
    },
    { timestamps: { createdAt: true, updatedAt: false } }
);

// Unique token — explicit for clarity (field-level unique: true is already
// a unique index, but this documents the intent).
ShareLinkSchema.index({ token: 1 }, { unique: true });

// orgId lookup — used when revoking all links for a given org.
ShareLinkSchema.index({ orgId: 1, createdAt: -1 });

module.exports = {
    modelName: "ShareLink",
    schema: ShareLinkSchema,
};
