#!/usr/bin/env node
/**
 * generateRoleTests.js
 *
 * Regenerates backend/tests/rolePermissions.generated.contract.test.js from the
 * current RBAC SSOT. The SSOT — `ORG_ROLE_PERMISSIONS` + the full resolution
 * pipeline (permissionRegistry → accessResolver → authorityBridge) — is the
 * single authority; this script snapshots it into a Jest suite so any drift
 * (accidental or otherwise) surfaces as a failing contract test in CI.
 *
 * Regenerate after any intentional change to:
 *   - src/rbac/orgPermissions.js           (role → permission assignments)
 *   - src/rbac/permissionRegistry.js       (hierarchy / nested expansion)
 *   - src/rbac/accessResolver.js           (org-level set resolution)
 *   - src/core/security/authorityBridge.js (effective-permissions derivation)
 *
 * Usage:
 *   node backend/scripts/generateRoleTests.js
 */

"use strict";

const fs   = require("fs");
const path = require("path");

// Resolve @-aliases the SSOT uses by piggybacking on the backend's module-alias
// registration. Without this, `require("@rbac/...")` inside the pipeline blows up
// when we execute the script outside of Jest.
require("module-alias/register");

const { ORG_ROLES, ORG_ROLE_PERMISSIONS } = require("../src/rbac/orgPermissions");
const {
    generateRoleSeed,
    flattenPermissions,
} = require("../src/rbac/permissionRegistry");
const { resolvePermissionSet } = require("../src/rbac/accessResolver");
const { resolveAuthority }     = require("../src/core/security/authorityBridge");

// Bump when the pipeline's shape changes (not when a role gains/loses a
// permission — that's just a regeneration). Kept in sync with the stamp the
// previous hand-edited header carried.
const PERMISSION_VERSION = 9;

function effectiveForRole(role) {
    const nested = generateRoleSeed(role);
    const orgSet = resolvePermissionSet({ rolePermissions: nested, planModules: undefined });
    const authority = resolveAuthority({
        orgPermissionSet: orgSet,
        platformDesignation: null,
    });
    return {
        nestedFlat: [...flattenPermissions(nested)].sort(),
        resolved:   [...authority.effectivePermissions].sort(),
    };
}

function arr(list) {
    return "[" + list.map((s) => JSON.stringify(s)).join(",") + "]";
}

const header = `/**
 * rolePermissions.test.js — AUTO-GENERATED
 *
 * ⚠️  DO NOT EDIT THIS FILE BY HAND.
 *     Regenerate via: node backend/scripts/generateRoleTests.js
 *
 * Generated at:        ${new Date().toISOString()}
 * PERMISSION_VERSION:  ${PERMISSION_VERSION}
 *
 * What this suite proves:
 *   For every system role in ORG_ROLES, the full RBAC pipeline
 *     ORG_ROLE_PERMISSIONS → generateRoleSeed → resolvePermissionSet
 *                         → resolveAuthority → effective permissions
 *   produces EXACTLY the permissions baked into the SSOT at generation time.
 *
 * If this suite fails after a SSOT change, regenerate it and review the diff
 * before committing — a role's effective grants should only change with intent.
 */

"use strict";

const {
    ORG_ROLE_PERMISSIONS,
} = require("../src/rbac/orgPermissions");
const {
    generateRoleSeed,
    flattenPermissions,
} = require("../src/rbac/permissionRegistry");
const { resolvePermissionSet } = require("../src/rbac/accessResolver");
const { resolveAuthority } = require("../src/core/security/authorityBridge");

function effectiveForRole(role) {
    const nested = generateRoleSeed(role);
    const orgSet = resolvePermissionSet({ rolePermissions: nested, planModules: undefined });
    const authority = resolveAuthority({
        orgPermissionSet: orgSet,
        platformDesignation: null,
    });
    return {
        nestedFlat: [...flattenPermissions(nested)].sort(),
        resolved: [...authority.effectivePermissions].sort(),
    };
}

`;

let body = "";
for (const role of ORG_ROLES) {
    const baseline = [...(ORG_ROLE_PERMISSIONS[role] || [])].sort();
    const { nestedFlat, resolved } = effectiveForRole(role);

    body += `describe("RBAC pipeline — role \\"${role}\\"", () => {\n`;

    body += `    it("${role} baseline matches ORG_ROLE_PERMISSIONS SSOT", () => {\n`;
    body += `        const baseline = [...(ORG_ROLE_PERMISSIONS["${role}"] || [])].sort();\n`;
    body += `        expect(baseline).toEqual(${arr(baseline)});\n`;
    body += `    });\n\n`;

    body += `    it("${role} nested→flat matches expected", () => {\n`;
    body += `        const { nestedFlat } = effectiveForRole("${role}");\n`;
    body += `        expect(nestedFlat).toEqual(${arr(nestedFlat)});\n`;
    body += `    });\n\n`;

    body += `    it("${role} resolved pipeline matches expected", () => {\n`;
    body += `        const { resolved } = effectiveForRole("${role}");\n`;
    body += `        expect(resolved).toEqual(${arr(resolved)});\n`;
    body += `    });\n\n`;

    for (const perm of resolved) {
        body += `    it("${role} should resolve \\"${perm}\\"", () => {\n`;
        body += `        const { resolved } = effectiveForRole("${role}");\n`;
        body += `        expect(resolved).toContain("${perm}");\n`;
        body += `    });\n`;
    }

    body += `});\n\n`;
}

const outPath = path.join(__dirname, "..", "tests", "rolePermissions.generated.contract.test.js");
fs.writeFileSync(outPath, header + body.replace(/\n\n$/, "\n"));
console.log(`Wrote ${outPath}`);
console.log(`  roles:         ${ORG_ROLES.length}`);
console.log(`  total assertions ≈ ${ORG_ROLES.reduce((s, r) => s + 3 + effectiveForRole(r).resolved.length, 0)}`);
